import type { Metadata } from "next";
import "@/app/styles/main.scss";
import MainLayout from "./layouts/MainLayout";

export const metadata: Metadata = {
  title: "RESTATE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/bird-prey_15707391.png"
          type="image/x-icon"
        />
      </head>
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
